### ISSUE TITLE
ДЗ autoservice- есть вопросы

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/autoservice#2]
Удалось развернуть приложение на HEROKU, но работает оно кривовато:
1. не отображается картинка,
2. decription отображается не в виде текста, а в виде абракадабры.
Также есть вопросы по методам:
1. В AutoService: что означают вот эти строки и откуда взялась :
  public AutoService() throws NamingException, SQLException {
  var context = new InitialContext();
  ds = (DataSource) context.lookup("java:/comp/env/jdbc/db");
2. В FileService:
2.1. что делает этот метод?  
public FileService() throws IOException {
        uploadPath = System.getenv("UPLOAD_PATH");
        Files.createDirectories(Paths.get(uploadPath));
    }
2.2. что делает этот метод?  
    public void readFile(String id, ServletOutputStream os) throws IOException {
        var path = Paths.get(uploadPath).resolve(id);
        Files.copy(path, os);
    }
2.3. зачем здесь какие-то части (part?) Это части запроса пользователя?
    public String writeFile(Part part) throws IOException {
        var id = UUID.randomUUID().toString();
        part.write(Paths.get(uploadPath).resolve(id).toString());
        return id;
    }

**Comment by coursar** [comment]
1 - разобрали на лекции
2 - см `<request-character-encoding>` в `web.xml` - нужно UTF-8
3 - поиск по JNDI (то, что объявлено в файле `context.xml`)
4 - Получает переменные окружения
5 - Сохраняет файл
6 - Это Multipart запрос (см.презентации)
