### ISSUE TITLE
по русски все равно не работает:-(

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/autoservice#4]
Я добавила toLowerCase в метод create, чтобы в базу данных записывать сразу строчными буквами. Это получилось (например, наименование Mersedes записывается как mersedes), но по-русски все равно не работает. Может быть, еще что-то нужно сделать?

 public void create(String name, String description, String image) throws SQLException {
        try (var conn = ds.getConnection()) {
            try (var stmt = conn.prepareStatement("INSERT INTO autos (id, name, description, image) VALUES (?, ?, ?, ?)")) {
                stmt.setString(1, UUID.randomUUID().toString());
                stmt.setString(2, name.toLowerCase());
                stmt.setString(3, description);
                stmt.setString(4, image);
                stmt.execute();

            }
        }
    }

**Comment by coursar** [comment]
В web.xml добавьте следующие строки:
```xml
    <request-character-encoding>UTF-8</request-character-encoding>
    <response-character-encoding>UTF-8</response-character-encoding>
```
